-- AUTOGENERATED

local _, _addon = ...;

local mp5Spells = {
    [18378] = 8,
    [18379] = 6,
    [20959] = 10,
    [21360] = 2,
    [21361] = 3,
    [21362] = 4,
    [21363] = 5,
    [21364] = 7,
    [21365] = 9,
    [21366] = 11,
    [21618] = 4,
    [21619] = 4,
    [21620] = 5,
    [21623] = 2,
    [21624] = 2,
    [21625] = 3,
    [21626] = 6,
    [21627] = 6,
    [21628] = 7,
    [21629] = 8,
    [21631] = 9,
    [21632] = 10,
    [21633] = 10,
    [21634] = 11,
    [21635] = 12,
    [21636] = 12,
    [21640] = 14,
    [21641] = 14,
    [21643] = 15,
    [23212] = 16,
};

local hitSpells = {
    [15464] = 1,
    [15465] = 2,
    [15466] = 3,
};

local spellhitSpells = {
    [23727] = 1,
    [23729] = 2,
};

local spellPenSpells = {
    [25975] = 10,
    [26283] = 20,
    [28799] = 25,
    [28869] = 13,
};

_addon.itemData = {
    [7950] = { -- Armor of Thero-shan
        hit = hitSpells[15464],
    },
    [9448] = { -- Spidertank Oilrag
        mp5 = mp5Spells[21361],
    },
    [10659] = { -- Shard of Afrasa
        mp5 = mp5Spells[21363],
    },
    [10837] = { -- Tooth of Eranikus
        hit = hitSpells[15464],
    },
    [11634] = { -- Silkweb Gloves
        mp5 = mp5Spells[21625],
    },
    [11662] = { -- Ban'thok Sash
        spellHit = spellhitSpells[23727],
    },
    [11921] = { -- Impervious Giant
        hit = hitSpells[15464],
    },
    [11964] = { -- Swiftstrike Cudgel
        hit = hitSpells[15464],
    },
    [12082] = { -- Wyrmhide Spaulders
        hit = hitSpells[15465],
    },
    [12103] = { -- Star of Mystaria
        spellHit = spellhitSpells[23727],
    },
    [12637] = { -- Backusarian Gauntlets
        mp5 = mp5Spells[21618],
    },
    [12640] = { -- Lionheart Helm
        hit = hitSpells[15465],
    },
    [12651] = { -- Blackcrow
        hit = hitSpells[15464],
    },
    [12776] = { -- Enchanted Battlehammer
        hit = hitSpells[15465],
    },
    [12927] = { -- Truestrike Shoulders
        hit = hitSpells[15465],
    },
    [12936] = { -- Battleborn Armbraces
        hit = hitSpells[15464],
    },
    [12963] = { -- Blademaster Leggings
        hit = hitSpells[15464],
    },
    [12966] = { -- Blackmist Armguards
        hit = hitSpells[15464],
    },
    [13018] = { -- Executioner's Cleaver
        hit = hitSpells[15464],
    },
    [13052] = { -- Warmonger
        hit = hitSpells[15466],
    },
    [13056] = { -- Frenzied Striker
        hit = hitSpells[15465],
    },
    [13141] = { -- Tooth of Gnarr
        mp5 = mp5Spells[21361],
    },
    [13142] = { -- Brigam Girdle
        hit = hitSpells[15464],
    },
    [13178] = { -- Rosewine Circle
        mp5 = mp5Spells[21363],
    },
    [13179] = { -- Brazecore Armguards
        mp5 = mp5Spells[21361],
    },
    [13211] = { -- Slashclaw Bracers
        hit = hitSpells[15464],
    },
    [13216] = { -- Crown of the Penitent
        mp5 = mp5Spells[21626],
    },
    [13244] = { -- Gilded Gauntlets
        mp5 = mp5Spells[21362],
    },
    [13255] = { -- Trueaim Gauntlets
        hit = hitSpells[15464],
    },
    [13383] = { -- Woollies of the Prancing Minstrel
        mp5 = mp5Spells[21632],
    },
    [13386] = { -- Archivist Cape
        mp5 = mp5Spells[21618],
    },
    [13404] = { -- Mask of the Unforgiven
        hit = hitSpells[15465],
    },
    [13956] = { -- Clutch of Andros
        spellHit = spellhitSpells[23727],
    },
    [13963] = { -- Voone's Vice Grips
        hit = hitSpells[15465],
    },
    [13967] = { -- Windreaver Greaves
        hit = hitSpells[15464],
    },
    [14141] = { -- Ghostweave Vest
        mp5 = mp5Spells[18378],
    },
    [14142] = { -- Ghostweave Gloves
        mp5 = mp5Spells[18379],
    },
    [14143] = { -- Ghostweave Belt
        mp5 = mp5Spells[18379],
    },
    [14144] = { -- Ghostweave Pants
        mp5 = mp5Spells[18378],
    },
    [14154] = { -- Truefaith Vestments
        mp5 = mp5Spells[18379],
    },
    [14545] = { -- Ghostloom Leggings
        mp5 = mp5Spells[21627],
    },
    [14616] = { -- Bloodmail Boots
        hit = hitSpells[15464],
    },
    [14620] = { -- Deathbone Girdle
        mp5 = mp5Spells[21362],
    },
    [14621] = { -- Deathbone Sabatons
        mp5 = mp5Spells[21626],
    },
    [14622] = { -- Deathbone Gauntlets
        mp5 = mp5Spells[21362],
    },
    [14623] = { -- Deathbone Legguards
        mp5 = mp5Spells[21363],
    },
    [14624] = { -- Deathbone Chestplate
        mp5 = mp5Spells[21363],
    },
    [16418] = { -- Lieutenant Commander's Leather Veil
        hit = hitSpells[15464],
    },
    [16437] = { -- Marshal's Silk Footwraps
        spellHit = spellhitSpells[23727],
    },
    [16444] = { -- Field Marshal's Silk Spaulders
        spellPen = spellPenSpells[25975],
    },
    [16453] = { -- Field Marshal's Leather Chestpiece
        hit = hitSpells[15464],
    },
    [16455] = { -- Field Marshal's Leather Mask
        hit = hitSpells[15464],
    },
    [16456] = { -- Marshal's Leather Leggings
        hit = hitSpells[15465],
    },
    [16457] = { -- Field Marshal's Leather Epaulets
        hit = hitSpells[15464],
    },
    [16462] = { -- Marshal's Chain Boots
        hit = hitSpells[15464],
    },
    [16468] = { -- Field Marshal's Chain Spaulders
        hit = hitSpells[15464],
    },
    [16472] = { -- Marshal's Lamellar Boots
        mp5 = mp5Spells[18379],
    },
    [16473] = { -- Field Marshal's Lamellar Chestplate
        mp5 = mp5Spells[21363],
    },
    [16474] = { -- Field Marshal's Lamellar Faceguard
        mp5 = mp5Spells[21363],
    },
    [16476] = { -- Field Marshal's Lamellar Pauldrons
        mp5 = mp5Spells[18379],
    },
    [16479] = { -- Marshal's Plate Legguards
        hit = hitSpells[15464],
    },
    [16480] = { -- Field Marshal's Plate Shoulderguards
        hit = hitSpells[15464],
    },
    [16483] = { -- Marshal's Plate Boots
        hit = hitSpells[15464],
    },
    [16506] = { -- Champion's Leather Headguard
        hit = hitSpells[15464],
    },
    [16536] = { -- Warlord's Silk Amice
        spellPen = spellPenSpells[25975],
    },
    [16539] = { -- General's Silk Boots
        spellHit = spellhitSpells[23727],
    },
    [16543] = { -- General's Plate Leggings
        hit = hitSpells[15464],
    },
    [16544] = { -- Warlord's Plate Shoulders
        hit = hitSpells[15464],
    },
    [16545] = { -- General's Plate Boots
        hit = hitSpells[15464],
    },
    [16561] = { -- Warlord's Leather Helm
        hit = hitSpells[15464],
    },
    [16562] = { -- Warlord's Leather Spaulders
        hit = hitSpells[15464],
    },
    [16563] = { -- Warlord's Leather Breastplate
        hit = hitSpells[15464],
    },
    [16564] = { -- General's Leather Legguards
        hit = hitSpells[15465],
    },
    [16568] = { -- Warlord's Chain Shoulders
        hit = hitSpells[15464],
    },
    [16569] = { -- General's Chain Boots
        hit = hitSpells[15464],
    },
    [16573] = { -- General's Mail Boots
        mp5 = mp5Spells[21363],
    },
    [16795] = { -- Arcanist Crown
        spellHit = spellhitSpells[23727],
    },
    [16797] = { -- Arcanist Mantle
        mp5 = mp5Spells[21618],
    },
    [16799] = { -- Arcanist Bindings
        mp5 = mp5Spells[21625],
    },
    [16801] = { -- Arcanist Gloves
        mp5 = mp5Spells[21618],
    },
    [16809] = { -- Felheart Robes
        spellHit = spellhitSpells[23727],
    },
    [16812] = { -- Gloves of Prophecy
        mp5 = mp5Spells[21626],
    },
    [16814] = { -- Pants of Prophecy
        mp5 = mp5Spells[21626],
    },
    [16817] = { -- Girdle of Prophecy
        mp5 = mp5Spells[21618],
    },
    [16819] = { -- Vambraces of Prophecy
        mp5 = mp5Spells[21624],
    },
    [16823] = { -- Nightslayer Shoulder Pads
        hit = hitSpells[15464],
    },
    [16826] = { -- Nightslayer Gloves
        hit = hitSpells[15464],
    },
    [16828] = { -- Cenarion Belt
        mp5 = mp5Spells[21618],
    },
    [16829] = { -- Cenarion Boots
        mp5 = mp5Spells[21625],
    },
    [16833] = { -- Cenarion Vestments
        mp5 = mp5Spells[21625],
    },
    [16835] = { -- Cenarion Leggings
        mp5 = mp5Spells[21362],
    },
    [16836] = { -- Cenarion Spaulders
        mp5 = mp5Spells[21618],
    },
    [16838] = { -- Earthfury Belt
        mp5 = mp5Spells[21618],
    },
    [16842] = { -- Earthfury Helmet
        mp5 = mp5Spells[21626],
    },
    [16843] = { -- Earthfury Legguards
        mp5 = mp5Spells[21627],
    },
    [16844] = { -- Earthfury Epaulets
        mp5 = mp5Spells[21618],
    },
    [16848] = { -- Giantstalker's Epaulets
        hit = hitSpells[15464],
    },
    [16852] = { -- Giantstalker's Gloves
        hit = hitSpells[15465],
    },
    [16854] = { -- Lawbringer Helm
        mp5 = mp5Spells[21619],
    },
    [16855] = { -- Lawbringer Legplates
        mp5 = mp5Spells[21625],
    },
    [16857] = { -- Lawbringer Bracers
        mp5 = mp5Spells[21618],
    },
    [16859] = { -- Lawbringer Boots
        mp5 = mp5Spells[21624],
    },
    [16863] = { -- Gauntlets of Might
        hit = hitSpells[15464],
    },
    [16900] = { -- Stormrage Cover
        mp5 = mp5Spells[21626],
    },
    [16901] = { -- Stormrage Legguards
        mp5 = mp5Spells[18379],
    },
    [16902] = { -- Stormrage Pauldrons
        mp5 = mp5Spells[21618],
    },
    [16903] = { -- Stormrage Belt
        mp5 = mp5Spells[21618],
    },
    [16905] = { -- Bloodfang Chestpiece
        hit = hitSpells[15465],
    },
    [16911] = { -- Bloodfang Bracers
        hit = hitSpells[15464],
    },
    [16914] = { -- Netherwind Crown
        mp5 = mp5Spells[21619],
    },
    [16917] = { -- Netherwind Mantle
        mp5 = mp5Spells[21619],
    },
    [16918] = { -- Netherwind Bindings
        mp5 = mp5Spells[21362],
    },
    [16922] = { -- Leggings of Transcendence
        mp5 = mp5Spells[21364],
    },
    [16937] = { -- Dragonstalker's Spaulders
        hit = hitSpells[15464],
    },
    [16938] = { -- Dragonstalker's Legguards
        hit = hitSpells[15464],
    },
    [16943] = { -- Bracers of Ten Storms
        mp5 = mp5Spells[18379],
    },
    [16948] = { -- Gauntlets of Ten Storms
        mp5 = mp5Spells[21626],
    },
    [16953] = { -- Judgement Spaulders
        mp5 = mp5Spells[21363],
    },
    [16954] = { -- Judgement Legplates
        mp5 = mp5Spells[21362],
    },
    [16956] = { -- Judgement Gauntlets
        mp5 = mp5Spells[21626],
    },
    [16958] = { -- Judgement Breastplate
        mp5 = mp5Spells[21363],
    },
    [17063] = { -- Band of Accuria
        hit = hitSpells[15465],
    },
    [17064] = { -- Shard of the Scale
        mp5 = mp5Spells[23212],
    },
    [17069] = { -- Striker's Mark
        hit = hitSpells[15464],
    },
    [17070] = { -- Fang of the Mystics
        mp5 = mp5Spells[21362],
    },
    [17105] = { -- Aurastone Hammer
        mp5 = mp5Spells[21363],
    },
    [17106] = { -- Malistar's Defender
        mp5 = mp5Spells[21365],
    },
    [17110] = { -- Seal of the Archmagus
        mp5 = mp5Spells[21361],
    },
    [17113] = { -- Amberseal Keeper
        mp5 = mp5Spells[21636],
    },
    [17602] = { -- Field Marshal's Headdress
        mp5 = mp5Spells[21362],
    },
    [17603] = { -- Marshal's Satin Pants
        mp5 = mp5Spells[21362],
    },
    [17605] = { -- Field Marshal's Satin Vestments
        mp5 = mp5Spells[21362],
    },
    [17623] = { -- Warlord's Satin Cowl
        mp5 = mp5Spells[21362],
    },
    [17624] = { -- Warlord's Satin Robes
        mp5 = mp5Spells[21362],
    },
    [17625] = { -- General's Satin Leggings
        mp5 = mp5Spells[21362],
    },
    [17710] = { -- Charstone Dirk
        mp5 = mp5Spells[21623],
    },
    [17713] = { -- Blackstone Ring
        hit = hitSpells[15464],
    },
    [17718] = { -- Gizlock's Hypertech Buckler
        mp5 = mp5Spells[21618],
    },
    [17741] = { -- Nature's Embrace
        mp5 = mp5Spells[18378],
    },
    [17743] = { -- Resurgence Rod
        mp5 = mp5Spells[18378],
    },
    [18103] = { -- Band of Rumination
        mp5 = mp5Spells[21620],
    },
    [18104] = { -- Feralsurge Girdle
        mp5 = mp5Spells[21629],
    },
    [18263] = { -- Flarecore Wraps
        mp5 = mp5Spells[21365],
    },
    [18282] = { -- Core Marksman Rifle
        hit = hitSpells[15464],
    },
    [18308] = { -- Clever Hat
        mp5 = mp5Spells[21364],
    },
    [18311] = { -- Quel'dorai Channeling Rod
        mp5 = mp5Spells[21629],
    },
    [18312] = { -- Energized Chestplate
        mp5 = mp5Spells[21363],
    },
    [18314] = { -- Ring of Demonic Guile
        mp5 = mp5Spells[21626],
    },
    [18323] = { -- Satyr's Bow
        hit = hitSpells[15464],
    },
    [18327] = { -- Whipvine Cord
        mp5 = mp5Spells[21626],
    },
    [18349] = { -- Gauntlets of Accuracy
        hit = hitSpells[15464],
    },
    [18371] = { -- Mindtap Talisman
        mp5 = mp5Spells[21366],
    },
    [18386] = { -- Padre's Trousers
        mp5 = mp5Spells[21626],
    },
    [18404] = { -- Onyxia Tooth Pendant
        hit = hitSpells[15464],
    },
    [18465] = { -- Royal Seal of Eldre'Thalas
        hit = hitSpells[15465],
    },
    [18468] = { -- Royal Seal of Eldre'Thalas
        mp5 = mp5Spells[18378],
    },
    [18469] = { -- Royal Seal of Eldre'Thalas
        mp5 = mp5Spells[21618],
    },
    [18477] = { -- Shaggy Leggings
        mp5 = mp5Spells[21629],
    },
    [18483] = { -- Mana Channeling Wand
        mp5 = mp5Spells[21619],
    },
    [18491] = { -- Lorespinner
        mp5 = mp5Spells[21361],
    },
    [18500] = { -- Tarnished Elven Ring
        hit = hitSpells[15464],
    },
    [18532] = { -- Mindsurge Robe
        mp5 = mp5Spells[20959],
    },
    [18536] = { -- Milli's Lexicon
        mp5 = mp5Spells[21626],
    },
    [18541] = { -- Puissant Cape
        hit = hitSpells[15464],
    },
    [18609] = { -- Anathema
        mp5 = mp5Spells[21364],
    },
    [18697] = { -- Coldstone Slippers
        mp5 = mp5Spells[21618],
    },
    [18698] = { -- Tattered Leather Hood
        hit = hitSpells[15464],
    },
    [18726] = { -- Magistrate's Cuffs
        mp5 = mp5Spells[21362],
    },
    [18730] = { -- Shadowy Laced Handwraps
        mp5 = mp5Spells[21363],
    },
    [18736] = { -- Plaguehound Leggings
        hit = hitSpells[15464],
    },
    [18739] = { -- Chitinous Plate Legguards
        mp5 = mp5Spells[21363],
    },
    [18743] = { -- Gracious Cape
        mp5 = mp5Spells[21627],
    },
    [18757] = { -- Diabolic Mantle
        mp5 = mp5Spells[21629],
    },
    [18800] = { -- TEST 1H Amberseal Keeper
        mp5 = mp5Spells[21636],
    },
    [18803] = { -- Finkle's Lava Dredger
        mp5 = mp5Spells[21365],
    },
    [18812] = { -- Wristguards of True Flight
        hit = hitSpells[15464],
    },
    [18872] = { -- Manastorm Leggings
        mp5 = mp5Spells[21640],
    },
    [18875] = { -- Salamander Scale Pants
        mp5 = mp5Spells[21365],
    },
    [19038] = { -- Ring of Subtlety
        mp5 = mp5Spells[21619],
    },
    [19047] = { -- Wisdom of the Timbermaw
        mp5 = mp5Spells[21362],
    },
    [19050] = { -- Mantle of the Timbermaw
        mp5 = mp5Spells[21626],
    },
    [19096] = { -- Frostwolf Advisor's Pendant
        mp5 = mp5Spells[21362],
    },
    [19098] = { -- Stormpike Sage's Pendant
        mp5 = mp5Spells[21362],
    },
    [19120] = { -- Rune of the Guard Captain
        hit = hitSpells[15464],
    },
    [19123] = { -- Everwarm Handwraps
        mp5 = mp5Spells[21618],
    },
    [19131] = { -- Snowblind Shoes
        mp5 = mp5Spells[21363],
    },
    [19137] = { -- Onslaught Girdle
        hit = hitSpells[15464],
    },
    [19303] = { -- Darkmoon Necklace
        mp5 = mp5Spells[18379],
    },
    [19308] = { -- Tome of Arcane Domination
        mp5 = mp5Spells[21625],
    },
    [19312] = { -- Lei of the Lifegiver
        mp5 = mp5Spells[21625],
    },
    [19325] = { -- Don Julio's Band
        hit = hitSpells[15464],
    },
    [19347] = { -- Claw of Chromaggus
        mp5 = mp5Spells[21618],
    },
    [19371] = { -- Pendant of the Fallen Dragon
        mp5 = mp5Spells[21365],
    },
    [19373] = { -- Black Brood Pauldrons
        mp5 = mp5Spells[21631],
    },
    [19374] = { -- Bracers of Arcane Accuracy
        spellHit = spellhitSpells[23727],
    },
    [19377] = { -- Prestor's Talisman of Connivery
        hit = hitSpells[15464],
    },
    [19379] = { -- Neltharion's Tear
        spellHit = spellhitSpells[23729],
    },
    [19381] = { -- Boots of the Shadow Flame
        hit = hitSpells[15465],
    },
    [19384] = { -- Master Dragonslayer's Ring
        hit = hitSpells[15464],
    },
    [19387] = { -- Chromatic Boots
        hit = hitSpells[15464],
    },
    [19388] = { -- Angelista's Grasp
        spellHit = spellhitSpells[23729],
    },
    [19390] = { -- Taut Dragonhide Gloves
        mp5 = mp5Spells[21627],
    },
    [19391] = { -- Shimmering Geta
        mp5 = mp5Spells[21636],
    },
    [19395] = { -- Rejuvenating Gem
        mp5 = mp5Spells[21365],
    },
    [19397] = { -- Ring of Blackrock
        mp5 = mp5Spells[21365],
    },
    [19400] = { -- Firemaw's Clutch
        mp5 = mp5Spells[21363],
    },
    [19401] = { -- Primalist's Linked Legguards
        spellHit = spellhitSpells[23727],
    },
    [19403] = { -- Band of Forced Concentration
        spellHit = spellhitSpells[23727],
    },
    [19406] = { -- Drake Fang Talisman
        hit = hitSpells[15465],
    },
    [19430] = { -- Shroud of Pure Thought
        mp5 = mp5Spells[21626],
    },
    [19435] = { -- Essence Gatherer
        mp5 = mp5Spells[21363],
    },
    [19438] = { -- Ringo's Blizzard Boots
        spellHit = spellhitSpells[23727],
    },
    [19518] = { -- Advisor's Ring
        mp5 = mp5Spells[21619],
    },
    [19519] = { -- Advisor's Ring
        mp5 = mp5Spells[21362],
    },
    [19520] = { -- Advisor's Ring
        mp5 = mp5Spells[21625],
    },
    [19521] = { -- Advisor's Ring
        mp5 = mp5Spells[21624],
    },
    [19522] = { -- Lorekeeper's Ring
        mp5 = mp5Spells[21619],
    },
    [19523] = { -- Lorekeeper's Ring
        mp5 = mp5Spells[21362],
    },
    [19524] = { -- Lorekeeper's Ring
        mp5 = mp5Spells[21625],
    },
    [19525] = { -- Lorekeeper's Ring
        mp5 = mp5Spells[21624],
    },
    [19566] = { -- Advisor's Gnarled Staff
        mp5 = mp5Spells[18378],
    },
    [19567] = { -- Advisor's Gnarled Staff
        mp5 = mp5Spells[21364],
    },
    [19568] = { -- Advisor's Gnarled Staff
        mp5 = mp5Spells[21626],
    },
    [19569] = { -- Advisor's Gnarled Staff
        mp5 = mp5Spells[21618],
    },
    [19570] = { -- Lorekeeper's Staff
        mp5 = mp5Spells[18378],
    },
    [19571] = { -- Lorekeeper's Staff
        mp5 = mp5Spells[21364],
    },
    [19572] = { -- Lorekeeper's Staff
        mp5 = mp5Spells[21626],
    },
    [19573] = { -- Lorekeeper's Staff
        mp5 = mp5Spells[21618],
    },
    [19682] = { -- Bloodvine Vest
        spellHit = spellhitSpells[23729],
    },
    [19683] = { -- Bloodvine Leggings
        spellHit = spellhitSpells[23727],
    },
    [19684] = { -- Bloodvine Boots
        spellHit = spellhitSpells[23727],
    },
    [19685] = { -- Primal Batskin Jerkin
        hit = hitSpells[15464],
    },
    [19686] = { -- Primal Batskin Gloves
        hit = hitSpells[15465],
    },
    [19687] = { -- Primal Batskin Bracers
        hit = hitSpells[15464],
    },
    [19693] = { -- Darksoul Breastplate
        hit = hitSpells[15464],
    },
    [19694] = { -- Darksoul Leggings
        hit = hitSpells[15465],
    },
    [19695] = { -- Darksoul Shoulders
        hit = hitSpells[15464],
    },
    [19829] = { -- Zandalar Augur's Belt
        mp5 = mp5Spells[21619],
    },
    [19830] = { -- Zandalar Augur's Bracers
        mp5 = mp5Spells[21362],
    },
    [19831] = { -- Zandalar Predator's Mantle
        mp5 = mp5Spells[21619],
    },
    [19832] = { -- Zandalar Predator's Belt
        hit = hitSpells[15464],
    },
    [19833] = { -- Zandalar Predator's Bracers
        mp5 = mp5Spells[21362],
    },
    [19835] = { -- Zandalar Madcap's Mantle
        hit = hitSpells[15464],
    },
    [19844] = { -- Zandalar Illusionist's Robe DEPRECATED
        spellHit = spellhitSpells[23729],
    },
    [19847] = { -- Zandalar Demoniac's Robe DEPRECATED
        spellHit = spellhitSpells[23729],
    },
    [19857] = { -- Cloak of Consumption
        spellHit = spellhitSpells[23727],
    },
    [19876] = { -- Soul Corrupter's Necklace
        spellHit = spellhitSpells[23727],
    },
    [19884] = { -- Jin'do's Judgement
        mp5 = mp5Spells[21641],
        spellHit = spellhitSpells[23729],
    },
    [19891] = { -- Jin'do's Bag of Whammies
        spellHit = spellhitSpells[23727],
    },
    [19893] = { -- Zanzil's Seal
        spellHit = spellhitSpells[23727],
    },
    [19903] = { -- Fang of Venoxis
        mp5 = mp5Spells[18379],
    },
    [19905] = { -- Zanzil's Band
        mp5 = mp5Spells[21618],
        spellHit = spellhitSpells[23727],
    },
    [19906] = { -- Blooddrenched Footpads
        hit = hitSpells[15464],
    },
    [19907] = { -- Zulian Tigerhide Cloak
        hit = hitSpells[15464],
    },
    [19920] = { -- Primalist's Band
        mp5 = mp5Spells[21626],
    },
    [19923] = { -- Jeklik's Opaline Talisman
        mp5 = mp5Spells[21625],
    },
    [19925] = { -- Band of Jin
        hit = hitSpells[15464],
    },
    [19929] = { -- Bloodtinged Gloves
        spellHit = spellhitSpells[23727],
    },
    [19946] = { -- Tigule's Harpoon
        hit = hitSpells[15465],
    },
    [19964] = { -- Renataki's Soul Conduit
        mp5 = mp5Spells[21627],
    },
    [19965] = { -- Wushoolay's Poker
        mp5 = mp5Spells[21627],
    },
    [19967] = { -- Thoughtblighter
        mp5 = mp5Spells[21363],
    },
    [19999] = { -- Bloodvine Goggles
        mp5 = mp5Spells[21365],
        spellHit = spellhitSpells[23729],
    },
    [20003] = { -- Devilsaur Claws
        hit = hitSpells[15464],
    },
    [20033] = { -- Zandalar Demoniac's Robe
        spellHit = spellhitSpells[23727],
    },
    [20034] = { -- Zandalar Illusionist's Robe
        spellHit = spellhitSpells[23727],
    },
    [20056] = { -- Highlander's Mail Pauldrons
        mp5 = mp5Spells[21618],
    },
    [20061] = { -- Highlander's Epaulets
        mp5 = mp5Spells[21618],
    },
    [20083] = { -- Hunting Spear
        mp5 = mp5Spells[21363],
    },
    [20135] = { -- 90 Epic Warrior Bracelets
        hit = hitSpells[15464],
    },
    [20136] = { -- 90 Epic Warrior Breastplate
        hit = hitSpells[15465],
    },
    [20138] = { -- 90 Epic Warrior Helm
        hit = hitSpells[15465],
    },
    [20145] = { -- 90 Epic Warrior Cloak
        hit = hitSpells[15464],
    },
    [20176] = { -- Defiler's Epaulets
        mp5 = mp5Spells[21618],
    },
    [20203] = { -- Defiler's Mail Pauldrons
        mp5 = mp5Spells[21618],
    },
    [20216] = { -- Belt of Preserved Heads
        hit = hitSpells[15464],
    },
    [20217] = { -- Belt of Tiny Heads
        mp5 = mp5Spells[21628],
    },
    [20218] = { -- Faded Hakkari Cloak
        mp5 = mp5Spells[21626],
    },
    [20257] = { -- Seafury Gauntlets
        mp5 = mp5Spells[21364],
    },
    [20262] = { -- Seafury Boots
        mp5 = mp5Spells[21363],
    },
    [20264] = { -- Peacekeeper Gauntlets
        mp5 = mp5Spells[21619],
    },
    [20265] = { -- Peacekeeper Boots
        mp5 = mp5Spells[18379],
    },
    [20266] = { -- Peacekeeper Leggings
        mp5 = mp5Spells[21364],
    },
    [20278] = { -- 90 Epic Rogue Bow
        mp5 = mp5Spells[21624],
    },
    [20325] = { -- 90 Epic Frost Bindings
        mp5 = mp5Spells[21619],
    },
    [20327] = { -- 90 Epic Frost Crown
        mp5 = mp5Spells[18378],
    },
    [20329] = { -- 90 Epic Frost Leggings
        mp5 = mp5Spells[18378],
    },
    [20331] = { -- 90 Epic Frost Robes
        mp5 = mp5Spells[18378],
    },
    [20332] = { -- 90 Epic Frost Neck
        mp5 = mp5Spells[21619],
    },
    [20333] = { -- 90 Epic Frost Ring
        mp5 = mp5Spells[21619],
    },
    [20334] = { -- 90 Epic Frost Staff
        mp5 = mp5Spells[21620],
    },
    [20335] = { -- 90 Epic Frost Wand
        mp5 = mp5Spells[21624],
    },
    [20336] = { -- 90 Epic Frost Shroud
        mp5 = mp5Spells[21619],
    },
    [20380] = { -- Dreamscale Breastplate
        mp5 = mp5Spells[21618],
    },
    [20425] = { -- Advisor's Gnarled Staff
        mp5 = mp5Spells[21361],
    },
    [20426] = { -- Advisor's Ring
        mp5 = mp5Spells[21360],
    },
    [20431] = { -- Lorekeeper's Ring
        mp5 = mp5Spells[21360],
    },
    [20434] = { -- Lorekeeper's Staff
        mp5 = mp5Spells[21361],
    },
    [20479] = { -- Spitfire Breastplate
        mp5 = mp5Spells[18379],
    },
    [20480] = { -- Spitfire Gauntlets
        mp5 = mp5Spells[21363],
    },
    [20481] = { -- Spitfire Bracers
        mp5 = mp5Spells[21362],
    },
    [20517] = { -- Razorsteel Shoulders
        hit = hitSpells[15464],
    },
    [20521] = { -- Fury Visor
        hit = hitSpells[15464],
    },
    [20536] = { -- Soul Harvester
        spellHit = spellhitSpells[23727],
    },
    [20537] = { -- Runed Stygian Boots
        mp5 = mp5Spells[21618],
    },
    [20538] = { -- Runed Stygian Leggings
        mp5 = mp5Spells[21626],
    },
    [20539] = { -- Runed Stygian Belt
        mp5 = mp5Spells[21625],
    },
    [20556] = { -- Wildstaff
        hit = hitSpells[15464],
    },
    [20581] = { -- Staff of Rampant Growth
        mp5 = mp5Spells[21634],
    },
    [20618] = { -- Gloves of Delusional Power
        mp5 = mp5Spells[21363],
    },
    [20621] = { -- Boots of the Endless Moor
        mp5 = mp5Spells[21625],
    },
    [20628] = { -- Deviate Growth Cap
        mp5 = mp5Spells[21629],
    },
    [20631] = { -- Mendicant's Slippers
        mp5 = mp5Spells[21632],
    },
    [20647] = { -- Black Crystal Dagger
        mp5 = mp5Spells[21618],
    },
    [20648] = { -- Cold Forged Hammer
        mp5 = mp5Spells[21625],
    },
    [20680] = { -- Abyssal Mail Pauldrons
        hit = hitSpells[15464],
    },
    [20683] = { -- Abyssal Plate Epaulets
        hit = hitSpells[15464],
    },
    [20685] = { -- Wavefront Necklace
        mp5 = mp5Spells[21629],
    },
    [20686] = { -- Abyssal Cloth Amice
        spellHit = spellhitSpells[23727],
    },
    [20689] = { -- Abyssal Leather Shoulders
        hit = hitSpells[15464],
    },
    [20698] = { -- Elemental Attuned Blade
        mp5 = mp5Spells[21625],
    },
    [20714] = { -- Sandstorm Boots
        mp5 = mp5Spells[21618],
    },
    [21179] = { -- Band of Earthen Wrath
        mp5 = mp5Spells[21361],
    },
    [21182] = { -- Band of Earthen Might
        hit = hitSpells[15464],
    },
    [21185] = { -- Earthcalm Orb
        mp5 = mp5Spells[21629],
    },
    [21186] = { -- Rockfury Bracers
        spellHit = spellhitSpells[23727],
    },
    [21187] = { -- Earthweave Cloak
        hit = hitSpells[15464],
    },
    [21189] = { -- Might of Cenarius
        hit = hitSpells[15464],
    },
    [21201] = { -- Signet Ring of the Bronze Dragonflight
        hit = hitSpells[15464],
    },
    [21202] = { -- Signet Ring of the Bronze Dragonflight
        hit = hitSpells[15464],
    },
    [21203] = { -- Signet Ring of the Bronze Dragonflight
        hit = hitSpells[15464],
    },
    [21204] = { -- Signet Ring of the Bronze Dragonflight
        hit = hitSpells[15464],
    },
    [21205] = { -- Signet Ring of the Bronze Dragonflight
        hit = hitSpells[15464],
    },
    [21206] = { -- Signet Ring of the Bronze Dragonflight
        mp5 = mp5Spells[21625],
    },
    [21207] = { -- Signet Ring of the Bronze Dragonflight
        mp5 = mp5Spells[21625],
    },
    [21208] = { -- Signet Ring of the Bronze Dragonflight
        mp5 = mp5Spells[21362],
    },
    [21209] = { -- Signet Ring of the Bronze Dragonflight
        mp5 = mp5Spells[21362],
    },
    [21210] = { -- Signet Ring of the Bronze Dragonflight
        mp5 = mp5Spells[21363],
    },
    [21244] = { -- Blessed Qiraji Pugio
        hit = hitSpells[15464],
    },
    [21273] = { -- Blessed Qiraji Acolyte Staff
        spellHit = spellhitSpells[23729],
    },
    [21275] = { -- Blessed Qiraji Augur Staff
        mp5 = mp5Spells[21643],
    },
    [21278] = { -- Stormshroud Gloves
        hit = hitSpells[15464],
    },
    [21311] = { -- Earth Warder's Vest
        mp5 = mp5Spells[21626],
    },
    [21330] = { -- Conqueror's Spaulders
        hit = hitSpells[15464],
    },
    [21332] = { -- Conqueror's Legguards
        hit = hitSpells[15464],
    },
    [21334] = { -- Doomcaller's Robes
        spellPen = spellPenSpells[26283],
    },
    [21335] = { -- Doomcaller's Mantle
        spellHit = spellhitSpells[23727],
        spellPen = spellPenSpells[25975],
    },
    [21337] = { -- Doomcaller's Circlet
        spellHit = spellhitSpells[23727],
    },
    [21338] = { -- Doomcaller's Footwraps
        spellPen = spellPenSpells[25975],
    },
    [21343] = { -- Enigma Robes
        spellPen = spellPenSpells[26283],
    },
    [21344] = { -- Enigma Boots
        mp5 = mp5Spells[21362],
        spellHit = spellhitSpells[23727],
    },
    [21345] = { -- Enigma Shoulderpads
        mp5 = mp5Spells[21362],
        spellPen = spellPenSpells[25975],
    },
    [21346] = { -- Enigma Leggings
        mp5 = mp5Spells[21620],
    },
    [21347] = { -- Enigma Circlet
        spellHit = spellhitSpells[23727],
    },
    [21348] = { -- Tiara of the Oracle
        mp5 = mp5Spells[21628],
        spellHit = spellhitSpells[23727],
    },
    [21349] = { -- Footwraps of the Oracle
        mp5 = mp5Spells[21625],
    },
    [21350] = { -- Mantle of the Oracle
        mp5 = mp5Spells[21625],
        spellPen = spellPenSpells[25975],
    },
    [21351] = { -- Vestments of the Oracle
        spellPen = spellPenSpells[25975],
    },
    [21352] = { -- Trousers of the Oracle
        mp5 = mp5Spells[21627],
    },
    [21354] = { -- Genesis Shoulderpads
        mp5 = mp5Spells[21625],
    },
    [21355] = { -- Genesis Boots
        mp5 = mp5Spells[21362],
        spellPen = spellPenSpells[25975],
    },
    [21356] = { -- Genesis Trousers
        mp5 = mp5Spells[21618],
    },
    [21359] = { -- Deathdealer's Boots
        hit = hitSpells[15464],
    },
    [21360] = { -- Deathdealer's Helm
        hit = hitSpells[15464],
    },
    [21361] = { -- Deathdealer's Spaulders
        hit = hitSpells[15464],
    },
    [21364] = { -- Deathdealer's Vest
        hit = hitSpells[15464],
    },
    [21373] = { -- Stormcaller's Footguards
        mp5 = mp5Spells[21362],
        spellPen = spellPenSpells[25975],
    },
    [21375] = { -- Stormcaller's Leggings
        mp5 = mp5Spells[21618],
    },
    [21376] = { -- Stormcaller's Pauldrons
        mp5 = mp5Spells[21625],
    },
    [21388] = { -- Avenger's Greaves
        mp5 = mp5Spells[21362],
    },
    [21390] = { -- Avenger's Legguards
        mp5 = mp5Spells[21618],
    },
    [21391] = { -- Avenger's Pauldrons
        mp5 = mp5Spells[21625],
    },
    [21394] = { -- Drape of Unyielding Strength
        hit = hitSpells[15464],
    },
    [21395] = { -- Blade of Eternal Justice
        mp5 = mp5Spells[21618],
    },
    [21397] = { -- Cape of Eternal Justice
        mp5 = mp5Spells[21363],
    },
    [21401] = { -- Scythe of the Unseen Path
        mp5 = mp5Spells[21361],
    },
    [21403] = { -- Cloak of the Unseen Path
        hit = hitSpells[15464],
    },
    [21404] = { -- Dagger of Veiled Shadows
        hit = hitSpells[15464],
    },
    [21406] = { -- Cloak of Veiled Shadows
        hit = hitSpells[15464],
    },
    [21408] = { -- Band of Unending Life
        mp5 = mp5Spells[21363],
    },
    [21410] = { -- Gavel of Infinite Wisdom
        mp5 = mp5Spells[21362],
    },
    [21411] = { -- Ring of Infinite Wisdom
        mp5 = mp5Spells[21363],
    },
    [21413] = { -- Blade of Vaulted Secrets
        spellHit = spellhitSpells[23727],
    },
    [21417] = { -- Ring of Unspoken Names
        spellHit = spellhitSpells[23727],
    },
    [21452] = { -- Staff of the Ruins
        spellHit = spellhitSpells[23727],
    },
    [21455] = { -- Southwind Helm
        hit = hitSpells[15464],
    },
    [21458] = { -- Gauntlets of New Life
        mp5 = mp5Spells[21618],
    },
    [21459] = { -- Crossbow of Imminent Doom
        hit = hitSpells[15464],
    },
    [21462] = { -- Gloves of Dark Wisdom
        mp5 = mp5Spells[21363],
    },
    [21463] = { -- Ossirian's Binding
        hit = hitSpells[15464],
    },
    [21464] = { -- Shackles of the Unscarred
        spellPen = spellPenSpells[25975],
    },
    [21477] = { -- Ring of Fury
        hit = hitSpells[15464],
    },
    [21481] = { -- Boots of the Desert Protector
        mp5 = mp5Spells[21619],
    },
    [21482] = { -- Boots of the Fiery Sands
        mp5 = mp5Spells[21619],
    },
    [21483] = { -- Ring of the Desert Winds
        mp5 = mp5Spells[21625],
    },
    [21490] = { -- Slime Kickers
        hit = hitSpells[15464],
    },
    [21496] = { -- Bracers of Qiraji Command
        mp5 = mp5Spells[21362],
    },
    [21500] = { -- Belt of the Inquisition
        mp5 = mp5Spells[21618],
    },
    [21507] = { -- Amulet of the Shifting Sands
        mp5 = mp5Spells[21627],
    },
    [21517] = { -- Gnomish Turban of Psychic Might
        mp5 = mp5Spells[21365],
    },
    [21563] = { -- Don Rodrigo's Band
        spellPen = spellPenSpells[26283],
    },
    [21565] = { -- Rune of Perfection
        spellPen = spellPenSpells[26283],
    },
    [21566] = { -- Rune of Perfection
        spellPen = spellPenSpells[25975],
    },
    [21581] = { -- Gauntlets of Annihilation
        hit = hitSpells[15464],
    },
    [21582] = { -- Grasp of the Old God
        mp5 = mp5Spells[21364],
    },
    [21583] = { -- Cloak of Clarity
        mp5 = mp5Spells[18378],
    },
    [21585] = { -- Dark Storm Gauntlets
        spellHit = spellhitSpells[23727],
    },
    [21586] = { -- Belt of Never-ending Agony
        hit = hitSpells[15464],
    },
    [21587] = { -- Wristguards of Castigation
        mp5 = mp5Spells[21619],
    },
    [21588] = { -- Wristguards of Elemental Fury
        mp5 = mp5Spells[18379],
    },
    [21594] = { -- Bracers of the Fallen Son
        spellHit = spellhitSpells[23727],
    },
    [21597] = { -- Royal Scepter of Vek'lor
        spellHit = spellhitSpells[23727],
    },
    [21602] = { -- Qiraji Execution Bracers
        hit = hitSpells[15464],
    },
    [21607] = { -- Grasp of the Fallen Emperor
        mp5 = mp5Spells[21363],
    },
    [21610] = { -- Wormscale Blocker
        mp5 = mp5Spells[21627],
    },
    [21612] = { -- Wormscale Stompers
        mp5 = mp5Spells[21620],
    },
    [21615] = { -- Don Rigoberto's Lost Hat
        mp5 = mp5Spells[21634],
    },
    [21619] = { -- Gloves of the Messiah
        mp5 = mp5Spells[21633],
    },
    [21620] = { -- Ring of the Martyr
        mp5 = mp5Spells[21620],
    },
    [21663] = { -- Robes of the Guardian Saint
        mp5 = mp5Spells[21628],
    },
    [21666] = { -- Sartura's Might
        mp5 = mp5Spells[21620],
    },
    [21671] = { -- Robes of the Battleguard
        spellPen = spellPenSpells[26283],
    },
    [21672] = { -- Gloves of Enforcement
        hit = hitSpells[15464],
    },
    [21681] = { -- Ring of the Devoured
        mp5 = mp5Spells[18378],
    },
    [21688] = { -- Boots of the Fallen Hero
        hit = hitSpells[15464],
    },
    [21690] = { -- Angelista's Charm
        mp5 = mp5Spells[21626],
    },
    [21696] = { -- Robes of the Triumvirate
        mp5 = mp5Spells[21364],
    },
    [21698] = { -- Leggings of Immersion
        mp5 = mp5Spells[21627],
    },
    [21701] = { -- Cloak of Concentrated Hatred
        hit = hitSpells[15464],
    },
    [21707] = { -- Ring of Swarming Thought
        spellPen = spellPenSpells[26283],
    },
    [21709] = { -- Ring of the Fallen God
        spellHit = spellhitSpells[23727],
    },
    [21712] = { -- Amulet of the Fallen God
        mp5 = mp5Spells[18379],
    },
    [21801] = { -- Antenna of Invigoration
        mp5 = mp5Spells[21361],
    },
    [21806] = { -- Gavel of Qiraji Authority
        mp5 = mp5Spells[21626],
    },
    [21809] = { -- Fury of the Forgotten Swarm
        hit = hitSpells[15464],
    },
    [21814] = { -- Breastplate of Annihilation
        hit = hitSpells[15464],
    },
    [21838] = { -- Garb of Royal Ascension
        spellHit = spellhitSpells[23729],
    },
    [21839] = { -- Scepter of the False Prophet
        mp5 = mp5Spells[21625],
    },
    [21995] = { -- Boots of Heroism
        hit = hitSpells[15464],
    },
    [21997] = { -- Breastplate of Heroism
        hit = hitSpells[15464],
    },
    [22009] = { -- Darkmantle Tunic
        hit = hitSpells[15465],
    },
    [22013] = { -- Beastmaster's Cap
        hit = hitSpells[15464],
    },
    [22066] = { -- Sorcerer's Gloves
        spellHit = spellhitSpells[23727],
    },
    [22069] = { -- Sorcerer's Robes
        spellPen = spellPenSpells[26283],
    },
    [22074] = { -- Deathmist Mask
        spellHit = spellhitSpells[23727],
    },
    [22077] = { -- Deathmist Wraps
        spellHit = spellhitSpells[23727],
    },
    [22079] = { -- Virtuous Bracers
        mp5 = mp5Spells[21360],
    },
    [22080] = { -- Virtuous Crown
        mp5 = mp5Spells[21626],
    },
    [22083] = { -- Virtuous Robe
        mp5 = mp5Spells[21626],
    },
    [22084] = { -- Virtuous Sandals
        mp5 = mp5Spells[21628],
    },
    [22085] = { -- Virtuous Skirt
        mp5 = mp5Spells[21626],
    },
    [22086] = { -- Soulforge Belt
        mp5 = mp5Spells[21618],
    },
    [22087] = { -- Soulforge Boots
        mp5 = mp5Spells[21618],
    },
    [22093] = { -- Soulforge Spaulders
        mp5 = mp5Spells[21618],
    },
    [22096] = { -- Boots of The Five Thunders
        mp5 = mp5Spells[21618],
    },
    [22098] = { -- Cord of The Five Thunders
        mp5 = mp5Spells[21618],
    },
    [22099] = { -- Gauntlets of The Five Thunders
        mp5 = mp5Spells[21618],
    },
    [22107] = { -- Feralheart Boots
        mp5 = mp5Spells[21623],
    },
    [22112] = { -- Feralheart Spaulders
        mp5 = mp5Spells[21623],
    },
    [22113] = { -- Feralheart Vest
        mp5 = mp5Spells[21618],
    },
    [22150] = { -- Beads of Ogre Might
        hit = hitSpells[15464],
    },
    [22231] = { -- Kayser's Boots of Precision
        spellHit = spellhitSpells[23727],
    },
    [22232] = { -- Marksman's Girdle
        hit = hitSpells[15464],
    },
    [22234] = { -- Mantle of Lost Hope
        mp5 = mp5Spells[21625],
    },
    [22240] = { -- Greaves of Withering Despair
        spellHit = spellhitSpells[23727],
    },
    [22254] = { -- Wand of Eternal Light
        mp5 = mp5Spells[21624],
    },
    [22267] = { -- Spellweaver's Turban
        spellHit = spellhitSpells[23727],
    },
    [22271] = { -- Leggings of Frenzied Magic
        mp5 = mp5Spells[21363],
    },
    [22319] = { -- Tome of Divine Right
        mp5 = mp5Spells[21619],
    },
    [22326] = { -- Amalgam's Band
        mp5 = mp5Spells[21361],
    },
    [22329] = { -- Scepter of Interminable Focus
        spellHit = spellhitSpells[23727],
    },
    [22330] = { -- Shroud of Arcane Mastery
        spellHit = spellhitSpells[23727],
    },
    [22335] = { -- Lord Valthalak's Staff of Command
        spellHit = spellhitSpells[23727],
    },
    [22339] = { -- Rune Band of Wizardry
        spellHit = spellhitSpells[23727],
    },
    [22340] = { -- Pendant of Celerity
        hit = hitSpells[15464],
    },
    [22347] = { -- Fahrad's Reloading Repeater
        hit = hitSpells[15464],
    },
    [22348] = { -- Doomulus Prime
        hit = hitSpells[15464],
    },
    [22383] = { -- Sageblade
        spellPen = spellPenSpells[25975],
    },
    [22384] = { -- Persuader
        hit = hitSpells[15464],
    },
    [22385] = { -- Titanic Leggings
        hit = hitSpells[15465],
    },
    [22403] = { -- Diana's Pearl Necklace
        spellHit = spellhitSpells[23727],
    },
    [22411] = { -- Helm of the Executioner
        hit = hitSpells[15465],
    },
    [22416] = { -- Dreadnaught Breastplate
        hit = hitSpells[15465],
    },
    [22419] = { -- Dreadnaught Pauldrons
        hit = hitSpells[15464],
    },
    [22424] = { -- Redemption Wristguards
        mp5 = mp5Spells[21362],
    },
    [22425] = { -- Redemption Tunic
        mp5 = mp5Spells[20959],
    },
    [22426] = { -- Redemption Handguards
        mp5 = mp5Spells[21629],
    },
    [22427] = { -- Redemption Legguards
        mp5 = mp5Spells[21629],
    },
    [22428] = { -- Redemption Headpiece
        mp5 = mp5Spells[21629],
    },
    [22429] = { -- Redemption Spaulders
        mp5 = mp5Spells[21619],
    },
    [22430] = { -- Redemption Boots
        mp5 = mp5Spells[21363],
    },
    [22431] = { -- Redemption Girdle
        mp5 = mp5Spells[21363],
    },
    [22436] = { -- Cryptstalker Tunic
        mp5 = mp5Spells[21618],
        hit = hitSpells[15464],
    },
    [22437] = { -- Cryptstalker Legguards
        mp5 = mp5Spells[21627],
    },
    [22438] = { -- Cryptstalker Headpiece
        mp5 = mp5Spells[21625],
    },
    [22440] = { -- Cryptstalker Boots
        hit = hitSpells[15464],
    },
    [22441] = { -- Cryptstalker Handguards
        mp5 = mp5Spells[21618],
    },
    [22442] = { -- Cryptstalker Girdle
        mp5 = mp5Spells[21625],
        hit = hitSpells[15464],
    },
    [22443] = { -- Cryptstalker Wristguards
        hit = hitSpells[15464],
    },
    [22458] = { -- Moonshadow Stave
        mp5 = mp5Spells[21364],
    },
    [22464] = { -- Earthshatter Tunic
        mp5 = mp5Spells[21635],
    },
    [22465] = { -- Earthshatter Legguards
        mp5 = mp5Spells[21365],
    },
    [22466] = { -- Earthshatter Headpiece
        mp5 = mp5Spells[21629],
    },
    [22467] = { -- Earthshatter Spaulders
        mp5 = mp5Spells[21626],
    },
    [22468] = { -- Earthshatter Boots
        mp5 = mp5Spells[21626],
    },
    [22469] = { -- Earthshatter Handguards
        mp5 = mp5Spells[21626],
    },
    [22470] = { -- Earthshatter Girdle
        mp5 = mp5Spells[21628],
    },
    [22471] = { -- Earthshatter Wristguards
        mp5 = mp5Spells[21619],
    },
    [22476] = { -- Bonescythe Breastplate
        hit = hitSpells[15464],
    },
    [22477] = { -- Bonescythe Legplates
        hit = hitSpells[15464],
    },
    [22478] = { -- Bonescythe Helmet
        hit = hitSpells[15464],
    },
    [22479] = { -- Bonescythe Pauldrons
        hit = hitSpells[15464],
    },
    [22480] = { -- Bonescythe Sabatons
        hit = hitSpells[15464],
    },
    [22481] = { -- Bonescythe Gauntlets
        hit = hitSpells[15464],
    },
    [22488] = { -- Dreamwalker Tunic
        mp5 = mp5Spells[18378],
    },
    [22489] = { -- Dreamwalker Legguards
        mp5 = mp5Spells[18378],
    },
    [22491] = { -- Dreamwalker Spaulders
        mp5 = mp5Spells[21363],
    },
    [22492] = { -- Dreamwalker Boots
        mp5 = mp5Spells[21363],
    },
    [22494] = { -- Dreamwalker Girdle
        mp5 = mp5Spells[21618],
    },
    [22495] = { -- Dreamwalker Wristguards
        mp5 = mp5Spells[21620],
    },
    [22496] = { -- Frostfire Robe
        spellHit = spellhitSpells[23727],
    },
    [22497] = { -- Frostfire Leggings
        spellHit = spellhitSpells[23727],
    },
    [22498] = { -- Frostfire Circlet
        spellHit = spellhitSpells[23727],
    },
    [22502] = { -- Frostfire Belt
        spellHit = spellhitSpells[23727],
    },
    [22503] = { -- Frostfire Bindings
        spellPen = spellPenSpells[25975],
    },
    [22504] = { -- Plagueheart Robe
        spellHit = spellhitSpells[23727],
    },
    [22505] = { -- Plagueheart Leggings
        spellPen = spellPenSpells[25975],
    },
    [22506] = { -- Plagueheart Circlet
        spellHit = spellhitSpells[23727],
    },
    [22507] = { -- Plagueheart Shoulderpads
        spellHit = spellhitSpells[23727],
    },
    [22512] = { -- Robe of Faith
        mp5 = mp5Spells[21363],
    },
    [22514] = { -- Circlet of Faith
        mp5 = mp5Spells[21620],
    },
    [22515] = { -- Shoulderpads of Faith
        mp5 = mp5Spells[21361],
    },
    [22516] = { -- Sandals of Faith
        mp5 = mp5Spells[21626],
    },
    [22517] = { -- Gloves of Faith
        mp5 = mp5Spells[21362],
    },
    [22589] = { -- Atiesh, Greatstaff of the Guardian
        spellHit = spellhitSpells[23729],
    },
    [22651] = { -- Outrider's Plate Legguards
        hit = hitSpells[15464],
    },
    [22672] = { -- Sentinel's Plate Legguards
        hit = hitSpells[15464],
    },
    [22673] = { -- Outrider's Chain Leggings
        hit = hitSpells[15464],
    },
    [22676] = { -- Outrider's Mail Leggings
        mp5 = mp5Spells[18379],
    },
    [22681] = { -- Band of Piety
        mp5 = mp5Spells[21362],
    },
    [22691] = { -- Corrupted Ashbringer
        hit = hitSpells[15464],
    },
    [22713] = { -- Zulian Scepter of Rites
        mp5 = mp5Spells[21362],
    },
    [22714] = { -- Sacrificial Gauntlets
        hit = hitSpells[15464],
    },
    [22718] = { -- Blooddrenched Mask
        hit = hitSpells[15465],
    },
    [22731] = { -- Cloak of the Devoured
        spellHit = spellhitSpells[23727],
    },
    [22732] = { -- Mark of C'Thun
        hit = hitSpells[15464],
    },
    [22748] = { -- Sentinel's Chain Leggings
        hit = hitSpells[15464],
    },
    [22753] = { -- Sentinel's Lamellar Legguards
        hit = hitSpells[15464],
    },
    [22799] = { -- Soulseeker
        spellPen = spellPenSpells[28799],
    },
    [22800] = { -- Brimstone Staff
        spellHit = spellhitSpells[23729],
    },
    [22801] = { -- Spire of Twilight
        mp5 = mp5Spells[21632],
    },
    [22802] = { -- Kingsfall
        hit = hitSpells[15464],
    },
    [22804] = { -- Maexxna's Fang
        hit = hitSpells[15464],
    },
    [22806] = { -- Widow's Remorse
        hit = hitSpells[15464],
    },
    [22807] = { -- Wraith Blade
        spellHit = spellhitSpells[23727],
    },
    [22808] = { -- The Castigator
        hit = hitSpells[15464],
    },
    [22809] = { -- Maul of the Redeemed Crusader
        mp5 = mp5Spells[21629],
    },
    [22819] = { -- Shield of Condemnation
        mp5 = mp5Spells[18379],
    },
    [22820] = { -- Wand of Fates
        spellHit = spellhitSpells[23727],
    },
    [22860] = { -- Blood Guard's Silk Walkers
        spellHit = spellhitSpells[23727],
    },
    [22879] = { -- Legionnaire's Leather Chestpiece
        hit = hitSpells[15464],
    },
    [22880] = { -- Legionnaire's Leather Legguards
        hit = hitSpells[15464],
    },
    [22882] = { -- Legionnaire's Satin Legguards
        mp5 = mp5Spells[21626],
    },
    [22885] = { -- Legionnaire's Satin Tunic
        mp5 = mp5Spells[21626],
    },
    [22937] = { -- Gem of Nerubis
        spellPen = spellPenSpells[25975],
    },
    [22938] = { -- Cryptfiend Silk Cloak
        hit = hitSpells[15464],
    },
    [22943] = { -- Malice Stone Pendant
        spellPen = spellPenSpells[28869],
    },
    [22947] = { -- Pendant of Forgotten Names
        mp5 = mp5Spells[21364],
    },
    [22954] = { -- Kiss of the Spider
        hit = hitSpells[15464],
    },
    [22960] = { -- Cloak of Suturing
        mp5 = mp5Spells[21363],
    },
    [22988] = { -- The End of Dreams
        mp5 = mp5Spells[21620],
    },
    [22994] = { -- Digested Hand of Power
        mp5 = mp5Spells[21632],
    },
    [23000] = { -- Plated Abomination Ribcage
        hit = hitSpells[15464],
    },
    [23014] = { -- Iblis, Blade of the Fallen Seraph
        hit = hitSpells[15464],
    },
    [23017] = { -- Veil of Eclipse
        spellPen = spellPenSpells[25975],
    },
    [23018] = { -- Signet of the Fallen Defender
        hit = hitSpells[15464],
    },
    [23025] = { -- Seal of the Damned
        spellHit = spellhitSpells[23727],
    },
    [23027] = { -- Warmth of Forgiveness
        mp5 = mp5Spells[21632],
    },
    [23030] = { -- Cloak of the Scourge
        hit = hitSpells[15464],
    },
    [23031] = { -- Band of the Inevitable
        spellHit = spellhitSpells[23727],
    },
    [23037] = { -- Ring of Spiritual Fervor
        mp5 = mp5Spells[21632],
    },
    [23038] = { -- Band of Unnatural Forces
        hit = hitSpells[15464],
    },
    [23044] = { -- Harbinger of Doom
        hit = hitSpells[15464],
    },
    [23048] = { -- Sapphiron's Right Eye
        mp5 = mp5Spells[21619],
    },
    [23049] = { -- Sapphiron's Left Eye
        spellHit = spellhitSpells[23727],
    },
    [23050] = { -- Cloak of the Necropolis
        spellHit = spellhitSpells[23727],
    },
    [23056] = { -- Hammer of the Twisting Nether
        mp5 = mp5Spells[18378],
    },
    [23058] = { -- Life Channeling Necklace
        mp5 = mp5Spells[18379],
    },
    [23060] = { -- Bonescythe Ring
        hit = hitSpells[15464],
    },
    [23065] = { -- Ring of the Earthshatterer
        mp5 = mp5Spells[21626],
    },
    [23066] = { -- Ring of Redemption
        mp5 = mp5Spells[21627],
    },
    [23067] = { -- Ring of the Cryptstalker
        mp5 = mp5Spells[18379],
    },
    [23072] = { -- Fists of the Unrelenting
        hit = hitSpells[15464],
    },
    [23075] = { -- Death's Bargain
        mp5 = mp5Spells[21618],
    },
    [23219] = { -- Girdle of the Mentor
        hit = hitSpells[15464],
    },
    [23242] = { -- Claw of the Frost Wyrm
        hit = hitSpells[15464],
    },
    [23244] = { -- Champion's Plate Helm
        hit = hitSpells[15464],
    },
    [23257] = { -- Champion's Leather Helm
        hit = hitSpells[15464],
    },
    [23258] = { -- Champion's Leather Shoulders
        hit = hitSpells[15464],
    },
    [23261] = { -- Champion's Satin Hood
        mp5 = mp5Spells[21626],
    },
    [23262] = { -- Champion's Satin Mantle
        mp5 = mp5Spells[21626],
    },
    [23291] = { -- Knight-Lieutenant's Silk Walkers
        spellHit = spellhitSpells[23727],
    },
    [23298] = { -- Knight-Captain's Leather Chestpiece
        hit = hitSpells[15464],
    },
    [23299] = { -- Knight-Captain's Leather Legguards
        hit = hitSpells[15464],
    },
    [23302] = { -- Knight-Captain's Satin Legguards
        mp5 = mp5Spells[21626],
    },
    [23303] = { -- Knight-Captain's Satin Tunic
        mp5 = mp5Spells[21626],
    },
    [23312] = { -- Lieutenant Commander's Leather Helm
        hit = hitSpells[15464],
    },
    [23313] = { -- Lieutenant Commander's Leather Shoulders
        hit = hitSpells[15464],
    },
    [23314] = { -- Lieutenant Commander's Plate Helm
        hit = hitSpells[15464],
    },
    [23316] = { -- Lieutenant Commander's Satin Hood
        mp5 = mp5Spells[21626],
    },
    [23317] = { -- Lieutenant Commander's Satin Mantle
        mp5 = mp5Spells[21626],
    },
    [23454] = { -- Grand Marshal's Warhammer
        mp5 = mp5Spells[21626],
    },
    [23455] = { -- Grand Marshal's Demolisher
        mp5 = mp5Spells[21364],
    },
    [23464] = { -- High Warlord's Battle Mace
        mp5 = mp5Spells[21626],
    },
    [23465] = { -- High Warlord's Destroyer
        mp5 = mp5Spells[21364],
    },
    [23663] = { -- Girdle of Elemental Fury
        mp5 = mp5Spells[21363],
    },
    [23664] = { -- Pauldrons of Elemental Fury
        spellHit = spellhitSpells[23727],
    },
    [23666] = { -- Belt of the Grand Crusader
        mp5 = mp5Spells[21364],
    },
    [23667] = { -- Spaulders of the Grand Crusader
        mp5 = mp5Spells[21618],
    },
};

